In [4]:
import polars as pl
import os

directory_path = "clean"

def rem():
    for filename in os.listdir(directory_path):
        if filename.startswith("cleaned"):
            new_name = filename.replace("cleaned", "", 1).lstrip("_ ")

            old_file_path = os.path.join(directory_path, filename)
            new_file_path = os.path.join(directory_path, new_name)

            try:
                os.rename(old_file_path, new_file_path)
                print(f"Renamed: '{filename}' -> '{new_name}'")
            except OSError as e:
                print(f"Error renaming {filename}: {e}")

print(os.listdir(directory_path))


biodf = pl.read_csv("BIOPRO_J.csv")
demodf = pl.read_csv("DEMO_J.csv")

['BIOPRO_J.csv', 'DR1TOT_J.csv', 'VIC_J.csv', 'VID_J.csv', 'DEMO_J.csv', 'MCQ_J.csv', 'SLQ_J.csv', 'DPQ_J.csv']

In [3]:
joined = biodf.join(demodf, on='SEQN', how='inner')
biodf

shape: (6_401, 41)
┌──────────┬──────────┬──────────┬────────┬───┬────────┬──────────┬────────┬──────────┐
│ SEQN     ┆ LBXSATSI ┆ LBDSATLC ┆ LBXSAL ┆ … ┆ LBXSTR ┆ LBDSTRSI ┆ LBXSUA ┆ LBDSUASI │
│ ---      ┆ ---      ┆ ---      ┆ ---    ┆   ┆ ---    ┆ ---      ┆ ---    ┆ ---      │
│ f64      ┆ f64      ┆ f64      ┆ f64    ┆   ┆ f64    ┆ f64      ┆ f64    ┆ f64      │
╞══════════╪══════════╪══════════╪════════╪═══╪════════╪══════════╪════════╪══════════╡
│ 93705.0  ┆ 16.0     ┆ 0.0      ┆ 4.4    ┆ … ┆ 95.0   ┆ 1.073    ┆ 5.8    ┆ 345.0    │
│ 93706.0  ┆ 10.0     ┆ 0.0      ┆ 4.4    ┆ … ┆ 92.0   ┆ 1.039    ┆ 8.0    ┆ 475.8    │
│ 93707.0  ┆ 13.0     ┆ 0.0      ┆ 5.2    ┆ … ┆ 110.0  ┆ 1.242    ┆ 5.5    ┆ 327.1    │
│ 93708.0  ┆ 19.0     ┆ 0.0      ┆ 3.9    ┆ … ┆ 72.0   ┆ 0.813    ┆ 4.5    ┆ 267.7    │
│ 93709.0  ┆ 15.0     ┆ 0.0      ┆ 3.7    ┆ … ┆ 132.0  ┆ 1.49     ┆ 6.2    ┆ 368.8    │
│ …        ┆ …        ┆ …        ┆ …      ┆ … ┆ …      ┆ …        ┆ …      ┆ …        │
│ 102952.0 ┆ 22.0     ┆ 0.0      ┆ 4.8    ┆ … ┆ 98.0   ┆ 1.106    ┆ 6.4    ┆ 380.7    │
│ 102953.0 ┆ 40.0     ┆ 0.0      ┆ 4.0    ┆ … ┆ 114.0  ┆ 1.287    ┆ 5.8    ┆ 345.0    │
│ 102954.0 ┆ 6.0      ┆ 0.0      ┆ 3.9    ┆ … ┆ 64.0   ┆ 0.723    ┆ 3.1    ┆ 184.4    │
│ 102955.0 ┆ 11.0     ┆ 0.0      ┆ 4.1    ┆ … ┆ 89.0   ┆ 1.005    ┆ 6.3    ┆ 374.7    │
│ 102956.0 ┆ 47.0     ┆ 0.0      ┆ 4.3    ┆ … ┆ 289.0  ┆ 3.263    ┆ 6.4    ┆ 380.7    │
└──────────┴──────────┴──────────┴────────┴───┴────────┴──────────┴────────┴──────────┘

In [8]:
demodf

shape: (9_254, 46)
┌──────────┬──────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ SEQN     ┆ SDDSRVYR ┆ RIDSTATR ┆ RIAGENDR ┆ … ┆ SDMVSTRA ┆ INDHHIN2 ┆ INDFMIN2 ┆ INDFMPIR │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64      ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════╪══════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 93703.0  ┆ 10.0     ┆ 2.0      ┆ 2.0      ┆ … ┆ 145.0    ┆ 15.0     ┆ 15.0     ┆ 5.0      │
│ 93704.0  ┆ 10.0     ┆ 2.0      ┆ 1.0      ┆ … ┆ 143.0    ┆ 15.0     ┆ 15.0     ┆ 5.0      │
│ 93705.0  ┆ 10.0     ┆ 2.0      ┆ 2.0      ┆ … ┆ 145.0    ┆ 3.0      ┆ 3.0      ┆ 0.82     │
│ 93706.0  ┆ 10.0     ┆ 2.0      ┆ 1.0      ┆ … ┆ 134.0    ┆ null     ┆ null     ┆ null     │
│ 93707.0  ┆ 10.0     ┆ 2.0      ┆ 1.0      ┆ … ┆ 138.0    ┆ 10.0     ┆ 10.0     ┆ 1.88     │
│ …        ┆ …        ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ 102952.0 ┆ 10.0     ┆ 2.0      ┆ 2.0      ┆ … ┆ 138.0    ┆ 4.0      ┆ 4.0      ┆ 0.95     │
│ 102953.0 ┆ 10.0     ┆ 2.0      ┆ 1.0      ┆ … ┆ 137.0    ┆ 12.0     ┆ 12.0     ┆ null     │
│ 102954.0 ┆ 10.0     ┆ 2.0      ┆ 2.0      ┆ … ┆ 144.0    ┆ 10.0     ┆ 10.0     ┆ 1.18     │
│ 102955.0 ┆ 10.0     ┆ 2.0      ┆ 2.0      ┆ … ┆ 136.0    ┆ 9.0      ┆ 9.0      ┆ 2.24     │
│ 102956.0 ┆ 10.0     ┆ 2.0      ┆ 1.0      ┆ … ┆ 142.0    ┆ 7.0      ┆ 7.0      ┆ 1.56     │
└──────────┴──────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘